#!/bin/bash

# critical
## Debian:
## sudo apt-get install python3-soundfile python3-scipy
## sudo pip3 install praat-parselmouth python-magic
sudo -H pip3 install -U python-magic soundfile scipy praat-parselmouth

# non-critical
## Debian:
## sudo apt-get install python3-pyaudio python3-dicom python3-cairosvg python3-pydub python3-pil.imagetk
## sudo pip3 install textgrid wav2vec
sudo -H pip3 install -U cairosvg wav2vec pygame numpy pillow pydicom textgrid

python3 ./setup.py build_ext --inplace

echo ''
echo 'Note: you will need to install some other packages to use the full'
echo '  functionality of this program for example, OSX users can try running'
echo '  this command:'
echo ''
echo '    $ brew install --upgrade cairo sdl sdl_mixer libmagic'
echo ''
