version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout

      - run:
          name: install system packages
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update
            apt-get install --yes \
                ffmpeg \
                portaudio19-dev \
                python3.8 \
                python3.8-venv \
                python3-pip \
                python3-tk

      - run: sudo pip install boto3 mypy_boto3_s3 nox
      - run: ./scripts/download-test-data
      - run: nox
