version: 2.1

commands:
  install-and-check:
    parameters:
      python:
        type: string

    steps:
      - run:
          name: upgrade pip and friends
          command: |
            << parameters.python >> -m pip install \
                pip==22.3 \
                setuptools==65.5.0 \
                wheel==0.38.0

      - run:
          name: install ultratrace
          command: |
            << parameters.python >> -m pip install \
                --requirement ./requirements-dev.txt

      - run: nox

jobs:
  ubuntu:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout

      - run:
          name: install system packages
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update
            apt-get install --yes \
                ffmpeg \
                portaudio19-dev \
                python3.8 \
                python3.8-dev \
                python3.8-venv \
                python3-pip \
                python3-tk

      - install-and-check:
          python: python3.8

workflows:
  main:
    jobs:
      - ubuntu
