version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout

      - run:
          name: install system packages
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update
            apt-get install --yes \
                ffmpeg \
                portaudio19-dev \
                python3.8 \
                python3.8-dev \
                python3.8-venv \
                python3-pip \
                python3-tk

      - run:
          name: upgrade pip and friends
          command: |
            python3.8 -m pip install \
                pip==22.3 \
                setuptools==65.5.0 \
                wheel==0.38.0

      - run:
          name: install ultratrace
          command: |
            python3.8 -m pip install \
                --requirement ./requirements-dev.txt

      - run: nox
