version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run: ./install.sh
      - run: ./scripts/download-test-data
      - run: sudo pip install nox
      - run: nox
