env:
  browser: true
  es6: true
  node: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - airbnb
  - 'plugin:prettier/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  sort-imports: off
  react/jsx-filename-extension:
    - error
    - extensions:
      - ".jsx"
      - ".tsx"
  import/extensions:
    - error
    - ignorePackages
    - tsx: never
      ts: never
      js: never
      jsx: never
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: "^_"
  '@typescript-eslint/no-empty-interface': off
  '@typescript-eslint/explicit-function-return-type':
    - error
    - allowExpressions: true
  '@typescript-eslint/camelcase': off
settings:
  import/resolver:
    node:
      paths:
        - src
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
        - .jpg
