#!/bin/bash

set -euo pipefail

mkdir -p test-data

cat <<DOWNLOAD | python3

import boto3

BUCKET = "swatphonlab"
PREFIX = "ultratrace-test-data"
KEYS = "$S3_KEYS".split()

s3 = boto3.client("s3")

for key in KEYS:
    s3.download_file(
        Bucket=BUCKET,
        Key=f"{PREFIX}/{key}",
        Filename=f"test-data/{key}",
    )

DOWNLOAD

ls test-data
